# Package Overview
package_name: classification_model

# Data Files
raw_data_file: raw.csv
training_data_file: train.csv
test_data_file: test.csv

# Variables
# The variable we are attempting to predict (final score)
target: final score

pipeline_name: score_classification_model
pipeline_save_file: score_classification_model_output_v

features:
  - index
  - number_of_siblings
  - direct_admission
  - CCA
  - learning_style
  - student_ID
  - gender
  - tuition
  - final_test
  - n_male
  - n_female
  - age
  - hours_per_week
  - attendance_rate
  - sleep_time
  - wake_time
  - mode_of_transport
  - bag_color

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

unused_fields:
  - index
  - student_ID
  - final_test
  - age
  - wake_time
  - mode_of_transport
  - bag_color

numerical_vars:
  - number_of_siblings
  - n_male
  - n_female
  - hours_per_week
  - attendance_rate

categorical_vars:
  - direct_admission
  - CCA
  - learning_style
  - gender
  - tuition
  - sleep_time

cabin_vars:
